#!/bin/bash

sudo yum install java -y

cd /opt
sudo wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.115/bin/apache-tomcat-9.0.115.tar.gz
sudo tar -xvf /opt/apache-tomcat-9.0.115.tar.gz

cd /opt/apache-tomcat-9.0.115/conf
sudo mv tomcat-users.xml tomcat-users_bkup.xml
sudo touch tomcat-users.xml
sudo echo '<?xml version="1.0" encoding="utf-8"?>
        <tomcat-users>
        <role rolename="manager-gui"/>
		<role rolename="manager-script"/>
        <role rolename="manager-status"/>
        <user username="tomcat" password="tomcat" roles="manager-gui, manager-script, manager-status"/>
        </tomcat-users>' > tomcat-users.xml

cd /opt/apache-tomcat-9.0.115/webapps/manager/META-INF
sudo sed -i '/CookieProcessor/,/HashMap"\/>/d' context.xml

sudo useradd tomcat
sudo chown -R tomcat:tomcat /opt/apache-tomcat-9.0.115


sudo tee /etc/systemd/system/tomcat.service > /dev/null <<EOF
[Unit]
Description=Apache Tomcat Web Application Container
After=network.target

[Service]
Type=forking
User=tomcat
Group=tomcat
ExecStart=/opt/apache-tomcat-9.0.115/bin/startup.sh
ExecStop=/opt/apache-tomcat-9.0.115/bin/shutdown.sh
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF


sudo systemctl daemon-reload
sudo systemctl enable tomcat
sudo systemctl start tomcat
sudo systemctl status tomcat
